# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=15)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
